package zwee.storage;

import java.util.List;
import java.util.stream.Collectors;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;

import zwee.ZweeException;
import zwee.parser.Parser;
import zwee.task.Task;
import zwee.task.TaskList;

public class Storage {

    private final File file;

    public Storage(String path) {
        this.file = new File(path);
        ensureParentDirectoryExists();
    }

    /**
     * Ensures that the storage file and its parent directories exist.
     */
    private void ensureParentDirectoryExists() {
        try {
            File parent = file.getParentFile();
            if (parent != null) {
                parent.mkdirs();
            }
            file.createNewFile();
        } catch (IOException e) {
            throw new ZweeException("Failed to initialize storage.");
        }
    }

    /**
     * Loads tasks from the storage file using Stream API.
     * Generated by Claude Haiku 4.5 using functional programming with Java Stream API.
     *
     * @return A list of tasks loaded from the file.
     */
    public List<Task> load() {
        assert this.file != null : "File should not be null";
        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            List<Task> tasks = br.lines()
                    .filter(line -> !line.trim().isEmpty())
                    .map(Parser::parseStoredTask)
                    .collect(Collectors.toList());
            return tasks;
        } catch (IOException e) {
            throw new ZweeException("Error loading tasks.");
        }
    }

    /**
     * Saves the given task list to the storage file using Stream API.
     * Generated by Claude Haiku 4.5 using functional programming with Java Stream API.
     *
     * @param taskList The task list to be saved.
     */
    public void save(TaskList taskList) {
        assert taskList != null : "TaskList should not be null";
        try (FileWriter fw = new FileWriter(file)) {
            String output = taskList.getAll().stream()
                    .map(Task::toFileString)
                    .collect(Collectors.joining(System.lineSeparator(), "", System.lineSeparator()));
            fw.write(output);
        } catch (IOException e) {
            throw new ZweeException("Error saving tasks.");
        }
    }
}